title: SMK 4 Malang - CAE
lang: en
description: Matapelajaran CAE untuk SMK 4 Malang. Pelajaran mengenai gambar teknik 3D menggunakan DesignSpark Mechanical dan mengolah hasil 3D kedalam aplikasi pengolah 3D printer.

## local method ##
# theme: jekyll-rtd-theme
# debug:
#   compress: false
#   dist: true
#   shortcodes: true

## remote method ##
remote_theme: rundocs/jekyll-rtd-theme

readme_index:
  with_frontmatter: true

exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions
